// <auto-generated />
namespace PremierLearn.Cursos.CursoWebapi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Migracao4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migracao4));
        
        string IMigrationMetadata.Id
        {
            get { return "201901032348125_Migracao4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
